const { Schema, model } = require("mongoose");

const CharacterSchema = new Schema(
  {
    generalInfo: {
      characterName: {
        type: String,
        default: "",
      },
      playerName: {
        type: String,
        default: "",
      },
      careerPath: {
        type: String,
        default: "",
      },
      experiencePoints: {
        type: Number,
        default: 5000,
      },
      homeWorld: {
        type: String,
        default: "",
      },
      motivation: {
        type: String,
        default: "",
      },
    },
    characteristics: {
      weaponSkill: {
        name: { type: String, default: "Ближний бой" },
        value: { type: Number, default: 0 },
        advancements: { type: Array, default: [false, false, false, false] },
      },
      ballisticSkill: {
        name: { type: String, default: "Дальний бой" },
        value: { type: Number, default: 0 },
        advancements: { type: Array, default: [false, false, false, false] },
      },
      strength: {
        name: { type: String, default: "Сила" },
        value: { type: Number, default: 0 },
        advancements: { type: Array, default: [false, false, false, false] },
      },
      toughness: {
        name: { type: String, default: "Выносливость" },
        value: { type: Number, default: 0 },
        advancements: { type: Array, default: [false, false, false, false] },
      },
      agility: {
        name: { type: String, default: "Ловкость" },
        value: { type: Number, default: 0 },
        advancements: { type: Array, default: [false, false, false, false] },
      },
      intelligence: {
        name: { type: String, default: "Интеллект" },
        value: { type: Number, default: 0 },
        advancements: { type: Array, default: [false, false, false, false] },
      },
      perception: {
        name: { type: String, default: "Восприятие" },
        value: { type: Number, default: 0 },
        advancements: { type: Array, default: [false, false, false, false] },
      },
      willPower: {
        name: { type: String, default: "Сила Воли" },
        value: { type: Number, default: 0 },
        advancements: { type: Array, default: [false, false, false, false] },
      },
      fellowship: {
        name: { type: String, default: "Товарищество" },
        value: { type: Number, default: 0 },
        advancements: { type: Array, default: [false, false, false, false] },
      },
    },
    skills: {
      type: Array,
      default: [
        {
          name: "Азартные игры",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Бартер",
          characteristic: "Тов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Бдительность",
          characteristic: "Вос",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Бесшумный шаг",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Запугивание",
          characteristic: "Сил",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Командование",
          characteristic: "Тов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Кутёж",
          characteristic: "Вын",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Лазанье",
          characteristic: "Сил",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Логика",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Маскировка",
          characteristic: "Тов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Обаяние",
          characteristic: "Тов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Обман",
          characteristic: "Тов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Оценка",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Плаванье",
          characteristic: "Сил",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Побег",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Поиск",
          characteristic: "Вос",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Проницательность",
          characteristic: "Вос",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Сбор информации",
          characteristic: "Тов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Скрытность",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Уклонение",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "basic",
        },
        {
          name: "Акробатика",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Безопасность",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Вождение",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Воззвание",
          characteristic: "СВ",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Выживание",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Выслеживание",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Грамотность",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Допрос",
          characteristic: "СВ",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Запретное знание",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Звероводство",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Исполнитель",
          characteristic: "Тов",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Ловкость рук",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Медика",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Навигация",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Обыденное знание",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Пилотирование",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Подрывное дело",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Пользование техники",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Психическое чутье",
          characteristic: "Вос",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Ремесло",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Слежка",
          characteristic: "Лов",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Тайный язык",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Торговля",
          characteristic: "Тов",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Трёп",
          characteristic: "Тов",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Учёное знание",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Химика",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Шифры",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
        {
          name: "Языкознание",
          characteristic: "Инт",
          levels: [false, false, false, false],
          bonus: false,
          type: "advanced",
        },
      ],
    },
    movement: {
      halfMove: { type: Number, default: 0 },
      fullMove: { type: Number, default: 0 },
      charge: { type: Number, default: 0 },
      run: { type: Number, default: 0 },
      baseLeap: { type: Number, default: 0 },
      baseJump: { type: Number, default: 0 },
    },
    user: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      unique: true,
    },
  },
  { timestamps: true, strict: false }
);

module.exports = model("Character", CharacterSchema);
